"""
Centralized constants for the SVU Helper Bot.
Now uses external JSON for internationalization (i18n).
"""
from utils.i18n import load_messages

# Load messages globally (at import time)
_msgs = load_messages("ar")

# --- STATUS CONSTANTS ---
# These match the English slug values stored in MongoDB (ProjectStatus enum values).
STATUS_PENDING               = "pending"
STATUS_ACCEPTED              = "accepted"
STATUS_AWAITING_VERIFICATION = "awaiting_verification"
STATUS_FINISHED              = "finished"
STATUS_OFFERED               = "offered"
STATUS_REJECTED_PAYMENT      = "rejected_payment"
STATUS_DENIED_ADMIN          = "denied_admin"
STATUS_DENIED_STUDENT        = "denied_student"

# Arabic display labels keyed by slug, sourced from locale file.
# Always use this dict for user-facing status text, never the raw slug.
STATUS_LABELS: dict = _msgs["status"]


# --- MESSAGES ---
MSG_WELCOME = _msgs["messages"]["welcome"]
MSG_HELP = _msgs["messages"]["help"]
MSG_CANCELLED = _msgs["messages"]["cancelled"]
MSG_NO_ACTIVE_PROCESS = _msgs["messages"]["no_active_process"]

# --- ADMIN DASHBOARD ---
MSG_ADMIN_DASHBOARD = _msgs["messages"]["admin_dashboard"]
MSG_BROADCAST_PROMPT = _msgs["messages"]["broadcast_prompt"]
MSG_BROADCAST_SUCCESS = _msgs["messages"]["broadcast_success"]
MSG_BROADCAST_SENDING = _msgs["messages"]["broadcast_sending"]
MSG_BROADCAST_WRAPPER = _msgs["messages"]["broadcast_wrapper"]
MSG_BROADCAST_ERROR = _msgs["messages"]["broadcast_error"]
MSG_PROJECT_DETAILS_HEADER = _msgs["messages"]["project_details_header"]
MSG_PROJECT_DETAIL_SUBJECT = _msgs["messages"]["project_detail_subject"]
MSG_PROJECT_DETAIL_TUTOR = _msgs["messages"]["project_detail_tutor"]
MSG_PROJECT_DETAIL_DEADLINE = _msgs["messages"]["project_detail_deadline"]
MSG_PROJECT_DETAIL_DETAILS = _msgs["messages"]["project_detail_details"]
MSG_PROJECT_DETAIL_FILE_HEADER = _msgs["messages"]["project_detail_file_header"]
MSG_MEDIA_FALLBACK_CAPTION = _msgs["messages"]["media_fallback_caption"]
MSG_ASK_PRICE = _msgs["messages"]["ask_price"]
MSG_ASK_DELIVERY = _msgs["messages"]["ask_delivery"]
MSG_ASK_NOTES = _msgs["messages"]["ask_notes"]
MSG_ASK_NOTES_TEXT = _msgs["messages"]["ask_notes_text"]
MSG_NO_NOTES = _msgs["messages"]["no_notes"]
MSG_OFFER_SENT = _msgs["messages"]["offer_sent"]
MSG_OFFER_NOTIFICATION = _msgs["messages"]["offer_notification"]
MSG_OFFER_SEND_ERROR = _msgs["messages"]["offer_send_error"]
MSG_UPLOAD_FINISHED_WORK = _msgs["messages"]["upload_finished_work"]
MSG_WORK_FINISHED_ALERT = _msgs["messages"]["work_finished_alert"]
MSG_FINISHED_CONFIRM = _msgs["messages"]["finished_confirm"]
MSG_FINISHED_NO_TEXT = _msgs["messages"]["finished_no_text"]
MSG_FINISH_ERROR = _msgs["messages"]["finish_error"]
MSG_PAYMENT_CONFIRMED_CLIENT = _msgs["messages"]["payment_confirmed_client"]
MSG_PAYMENT_CONFIRMED_ADMIN = _msgs["messages"]["payment_confirmed_admin"]
MSG_PAYMENT_REJECTED_CLIENT = _msgs["messages"]["payment_rejected_client"]
MSG_PAYMENT_REJECTED_ADMIN = _msgs["messages"]["payment_rejected_admin"]
MSG_PAYMENT_REJECTED_TO_STUDENT = _msgs["messages"]["payment_rejected_to_student"]
MSG_FILE_SEND_ERROR = _msgs["messages"]["file_send_error"]
MSG_NEW_PAYMENT_ADMIN_ALERT = _msgs["messages"]["new_payment_admin_alert"]
MSG_PROJECT_DENIED_CLIENT = _msgs["messages"]["project_denied_client"]
MSG_PROJECT_DENIED_STUDENT_TO_ADMIN = _msgs["messages"]["project_denied_student_to_admin"]
MSG_PROJECT_CLOSED = _msgs["messages"]["project_closed"]
MSG_PRICE_EMPTY = _msgs["messages"]["price_empty"]
MSG_PRICE_TOO_LONG = _msgs["messages"]["price_too_long"]
MSG_DELIVERY_EMPTY = _msgs["messages"]["delivery_empty"]
MSG_DELIVERY_TOO_LONG = _msgs["messages"]["delivery_too_long"]
MSG_NOTES_CHOOSE_HINT = _msgs["messages"]["notes_choose_hint"]
MSG_DATE_SELECTED_DEADLINE = _msgs["messages"]["date_selected_deadline"]
MSG_DATE_SELECTED_DELIVERY = _msgs["messages"]["date_selected_delivery"]
MSG_PENDING_PROJECTS_HEADER = _msgs["messages"]["pending_projects_header"]
MSG_ONGOING_PROJECTS_HEADER = _msgs["messages"]["ongoing_projects_header"]
MSG_STATS_REPORT = _msgs["messages"]["stats_report"]
MSG_MAINTENANCE_ON = _msgs["messages"]["maintenance_on"]
MSG_MAINTENANCE_OFF = _msgs["messages"]["maintenance_off"]
MSG_MAINTENANCE_ACTIVE = _msgs["messages"]["maintenance_active"]
MSG_GENERIC_ERROR = _msgs["messages"]["generic_error"]
MSG_GENERIC_ERROR_SHORT = _msgs["messages"]["generic_error_short"]
MSG_PERMISSION_DENIED = _msgs["messages"]["permission_denied"]
MSG_ADMIN_TICKETS_HEADER = _msgs["messages"]["admin_tickets_header"]
MSG_ADMIN_NO_OPEN_TICKETS = _msgs["messages"]["admin_no_open_tickets"]
MSG_ADMIN_USER_FALLBACK = _msgs["messages"]["admin_user_fallback"]
MSG_ADMIN_ATTACHMENT_LABEL = _msgs["messages"]["admin_attachment_label"]
MSG_ADMIN_LAST_MESSAGE = _msgs["messages"]["admin_last_message"]
MSG_ADMIN_TICKET_LINE = _msgs["messages"]["admin_ticket_line"]
MSG_TICKET_NEW_HEADER = _msgs["messages"]["ticket_new_header"]
MSG_TICKET_STUDENT_REPLY = _msgs["messages"]["ticket_student_reply"]
MSG_TICKET_CLOSED_WARNING = _msgs["messages"]["ticket_closed_warning"]
MSG_TICKET_ADMIN_REPLY_HEADER = _msgs["messages"]["ticket_admin_reply_header"]
MSG_TICKET_TOPIC_NAME = _msgs["messages"]["ticket_topic_name"]
MSG_SESSION_TIMEOUT = _msgs["messages"]["session_timeout"]
MSG_NO_URGENT_CASES = _msgs["messages"]["no_urgent_cases"]
MSG_URGENT_REPORT_HEADER = _msgs["messages"]["urgent_report_header"]

# --- MENU BUTTONS ---
BTN_NEW_PROJECT = _msgs["buttons"]["new_project"]
BTN_MY_PROJECTS = _msgs["buttons"]["my_projects"]
BTN_MY_OFFERS = _msgs["buttons"]["my_offers"]
BTN_BACK = _msgs["buttons"]["back"]
BTN_YES = _msgs["buttons"]["yes"]
BTN_NO = _msgs["buttons"]["no"]
BTN_CANCEL = _msgs["buttons"]["cancel"]
BTN_VIEW_ALL = _msgs["buttons"]["view_all"]
BTN_VIEW_PENDING = _msgs["buttons"]["view_pending"]
BTN_VIEW_ACCEPTED = _msgs["buttons"]["view_accepted"]
BTN_VIEW_HISTORY = _msgs["buttons"]["view_history"]
BTN_VIEW_PAYMENTS = _msgs["buttons"]["view_payments"]
BTN_BROADCAST = _msgs["buttons"]["broadcast"]
BTN_ADMIN_TICKETS = _msgs["buttons"]["admin_tickets"]
BTN_BACK_ICON = _msgs["buttons"]["back_icon"]
BTN_SEND_OFFER = _msgs["buttons"]["send_offer"]
BTN_REJECT = _msgs["buttons"]["reject"]
BTN_CONFIRM_PAYMENT = _msgs["buttons"]["confirm_payment"]
BTN_REJECT_PAYMENT = _msgs["buttons"]["reject_payment"]
BTN_ACCEPT_OFFER = _msgs["buttons"]["accept_offer"]
BTN_DENY_OFFER = _msgs["buttons"]["deny_offer"]
BTN_CANCEL_PAY = _msgs["buttons"]["cancel_pay"]
BTN_FINISH_PROJECT = _msgs["buttons"]["finish_project"]
BTN_MANAGE_PROJECT = _msgs["buttons"]["manage_project"]
BTN_SUPPORT = _msgs["buttons"]["support"]
BTN_VIEW_RECEIPT = _msgs["buttons"]["view_receipt"]
BTN_HELP = _msgs["buttons"]["help_btn"]
BTN_NO_SUBJECT = _msgs["buttons"]["no_subject"]
BTN_NEW_TICKET = _msgs["buttons"]["new_ticket"]
BTN_MY_OPEN_TICKETS = _msgs["buttons"]["my_open_tickets"]
BTN_CLOSED_TICKETS_LOG = _msgs["buttons"]["closed_tickets_log"]
BTN_SEND_REPLY = _msgs["buttons"]["send_reply"]
BTN_CLOSE_TICKET = _msgs["buttons"]["close_ticket"]
BTN_REOPEN_TICKET = _msgs["buttons"]["reopen_ticket"]
BTN_SEND_MORE = _msgs["buttons"]["send_more"]
BTN_DONE = _msgs["buttons"]["done"]
BTN_CONFIRM_DATE = _msgs["buttons"]["confirm_date"]
BTN_REJECT_DATE = _msgs["buttons"]["reject_date"]
BTN_URGENT_CASES = _msgs["buttons"]["urgent_cases"]

# --- CLIENT PROMPTS ---
MSG_ASK_SUBJECT = _msgs["client_prompts"]["ask_subject"]
MSG_ASK_TUTOR = _msgs["client_prompts"]["ask_tutor"]
MSG_ASK_DEADLINE = _msgs["client_prompts"]["ask_deadline"]
MSG_ASK_DETAILS = _msgs["client_prompts"]["ask_details"]
MSG_NO_DESC = _msgs["client_prompts"]["no_desc"]
MSG_PROJECT_SUBMITTED = _msgs["client_prompts"]["project_submitted"]
MSG_OFFER_ACCEPTED = _msgs["client_prompts"]["offer_accepted"]
MSG_PAYMENT_CANCELLED = _msgs["client_prompts"]["payment_cancelled"]
MSG_PAYMENT_PROOF_HINT = _msgs["client_prompts"]["payment_proof_hint"]
MSG_RECEIPT_RECEIVED = _msgs["client_prompts"]["receipt_received"]
MSG_OFFER_DETAILS = _msgs["client_prompts"]["offer_details"]
MSG_NO_PROJECTS = _msgs["client_prompts"]["no_projects"]
MSG_NO_OFFERS = _msgs["client_prompts"]["no_offers"]
MSG_SUBJECT_TOO_LONG = _msgs["client_prompts"]["subject_too_long"]
MSG_TUTOR_TOO_LONG = _msgs["client_prompts"]["tutor_too_long"]
MSG_DEADLINE_TOO_LONG = _msgs["client_prompts"]["deadline_too_long"]
MSG_MEDIA_BEFORE_TEXT = _msgs["client_prompts"]["media_before_text"]
MSG_FILE_TOO_LARGE = _msgs["client_prompts"]["file_too_large"]
MSG_PROJECT_SUBMIT_ERROR = _msgs["client_prompts"]["project_submit_error"]
MSG_PAYMENT_UPLOAD_ERROR = _msgs["client_prompts"]["payment_upload_error"]
MSG_PAYMENT_DOC_INVALID = _msgs["client_prompts"]["payment_doc_invalid"]
MSG_CANCEL_DONE = _msgs["client_prompts"]["cancel_done"]
MSG_DETAILS_RECEIVED = _msgs["client_prompts"]["details_received"]
MSG_SEND_NEXT = _msgs["client_prompts"]["send_next"]
MSG_INVALID_DATE_FORMAT = _msgs["client_prompts"]["invalid_date_format"]
MSG_INVALID_DATE_VALUES = _msgs["client_prompts"]["invalid_date_values"]
MSG_DATE_IN_PAST = _msgs["client_prompts"]["date_in_past"]
MSG_GEMINI_DATE_CONFIRM = _msgs["client_prompts"]["gemini_date_confirm"]
MSG_GEMINI_DATE_INVALID = _msgs["client_prompts"]["gemini_date_invalid"]
MSG_GEMINI_DATE_ACCEPTED = _msgs["client_prompts"]["gemini_date_accepted"]
MSG_GEMINI_DATE_REJECTED = _msgs["client_prompts"]["gemini_date_rejected"]

# --- TICKET MESSAGES ---
MSG_TICKET_SUPPORT_HUB = _msgs["tickets"]["support_hub"]
MSG_TICKET_NEW_PROMPT = _msgs["tickets"]["new_ticket_prompt"]
MSG_TICKET_SEND_TEXT = _msgs["tickets"]["send_text_or_file"]
MSG_TICKET_CREATED = _msgs["tickets"]["ticket_created"]
MSG_TICKET_CANCELLED = _msgs["tickets"]["cancelled"]
MSG_TICKET_CANCEL_ANSWER = _msgs["tickets"]["cancel_answer"]
MSG_TICKET_NO_OPEN = _msgs["tickets"]["no_open_tickets"]
MSG_TICKET_OPEN_HEADER = _msgs["tickets"]["open_tickets_header"]
MSG_TICKET_NOT_FOUND = _msgs["tickets"]["ticket_not_found"]
MSG_TICKET_STATUS_OPEN = _msgs["tickets"]["status_open"]
MSG_TICKET_STATUS_CLOSED = _msgs["tickets"]["status_closed"]
MSG_TICKET_VIEW_HEADER = _msgs["tickets"]["ticket_view_header"]
MSG_TICKET_PAGE_FOOTER = _msgs["tickets"]["page_footer"]
MSG_TICKET_ERROR_REOPEN = _msgs["tickets"]["error_reopen"]
MSG_TICKET_REPLY_PROMPT = _msgs["tickets"]["reply_prompt"]
MSG_TICKET_SEND_REPLY = _msgs["tickets"]["send_text_or_file_reply"]
MSG_TICKET_REPLY_ERROR = _msgs["tickets"]["reply_error"]
MSG_TICKET_REPLY_SUCCESS = _msgs["tickets"]["reply_success"]
MSG_TICKET_CLOSED_OR_MISSING = _msgs["tickets"]["ticket_closed_or_missing"]
MSG_TICKET_CLOSED_CONFIRM = _msgs["tickets"]["ticket_closed_confirm"]
MSG_TICKET_CLOSE_ERROR = _msgs["tickets"]["close_error"]
MSG_TICKET_NO_CLOSED = _msgs["tickets"]["no_closed_tickets"]
MSG_TICKET_CLOSED_HEADER = _msgs["tickets"]["closed_tickets_header"]
MSG_TICKET_REOPENED = _msgs["tickets"]["ticket_reopened"]
MSG_TICKET_REOPEN_ERROR = _msgs["tickets"]["reopen_error"]
MSG_TICKET_NO_MESSAGES = _msgs["tickets"]["no_messages"]
MSG_TICKET_SENDER_USER = _msgs["tickets"]["sender_user"]
MSG_TICKET_SENDER_SUPPORT = _msgs["tickets"]["sender_support"]
MSG_TICKET_FILE_LABEL = _msgs["tickets"]["file_label"]
MSG_TICKET_EMPTY_MESSAGE = _msgs["tickets"]["empty_message"]
